server:
  port: 8086


app:
  services:
    product-service.name: ${PRODUCT_SERVICE_NAME:localhost}
    product-service.port: ${PRODUCT_SERVICE_PORT:9093}
    shop-service.name: ${SHOP_SERVICE_NAME:localhost}
    shop-service.port: ${SHOP_SERVICE_PORT:10092}
    payment: http://localhost:8087/payment

  white-list: ","
  black-list: "/orders/**,/orders**,"


spring:
  application:
    name: order_service

  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/order_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka-3f4ed0b-tinhsinh2002-7811.c.aivencloud.com:23695
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  accessKey: ${ACCESS_KEY:}
grpc:
  server:
    port: 10096
