server:
  port: 8082

app:
  services:
    user: http://localhost:8081/user
    product: http://localhost:8083/product
  white-list: "/seller/register,"
  black-list: "/seller/orders,/seller/orders/**,/seller/products,/seller/products/**"


spring:
  application:
    name: shop-service

  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/shop_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
   ******
