server:
  port: 8081

grpc:
  server:
    port: 10091
    security:
      auth:
        enabled: false

spring:
  autoconfigure:
    exclude: net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
  application:
    name: user-service


  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/user_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: ${ACCESS_KEY:}
  refreshKey: ${REFRESH_KEY:}




