server:
  port: 8081

spring:
  application:
    name: user-service


  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/user_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=