server:
  port: 8080

app:
  api-prefix: /api

  services:
    auth: http://localhost:8081/auth

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/auth/**,${app.api-prefix}/user/**,${app.api-prefix}/admin/**,${app.api-prefix}/super-admin/**
          filters:
            - StripPrefix=1

        - id: shop-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/seller/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/email/**
          filters:
            - StripPrefix=1

        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=1

        - id: search-service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/search**
          filters:
            - StripPrefix=1

