server:
  port: 8080

app:
  api-prefix: /api

  services:
    auth: http://localhost:8081/auth

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/auth/**,${app.api-prefix}/user/**,${app.api-prefix}/admin/**,${app.api-prefix}/super-admin/**
          filters:
            - StripPrefix=1

        - id: shop-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/seller/**
          filters:
            - StripPrefix=1

