server:
  port: 8085


app:
  services:
    user: http://localhost:8081/user
    product: http://localhost:8083/product
  white-list: "/**,"
  black-list: ","


spring:
  application:
    name: cart_service



jwt:
  accessKey: ${ACCESS_KEY}