server:
  port: 8083

grpc:
  server:
    port: 9093

spring:
  application:
    name: product_service

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb://root:admin@localhost:27017/db_product?authSource=admin

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  # ? T?t SQL database

  jpa:
    hibernate:
      ddl-auto: update

app:
  white-list: "/product/{id},"
  black-list: "/product/**,"

jwt:
  accessKey: ${ACCESS_KEY:}


